### ISSUE TITLE
Duplicate Finder does not remove people without duplicates

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1883]
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When no potential duplicates are cleared for a entry, the entry does not clear from the duplicate finder. 

<img width="1163" alt="screen shot 2016-11-21 at 10 19 29 am copy" src="https://cloud.githubusercontent.com/assets/374209/20495127/a93fc09e-afd4-11e6-9fa1-1dbb11fb40de.png">

### Steps to Reproduce

1. Select an entry in the duplicate finder
2. Clear entries using the not duplicate button
3. Return to the duplicate finder, the cleared entry is still visible
4. Going back to the same entry results in the screenshot above.

**Expected behavior:** After the duplicates are removed, they should be removed from the list of potential duplicates.

**Actual behavior:** Even after the duplicate job is ran, the entry is still visible and cannot be removed.

### Versions

* **Rock Version:** 6.0
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
@garrettjohnson, Before I close this as unable to reproduce or fixed (because it may have been fixed in the develop branch) I want to make sure I tried this correctly.  Can you confirm?

Step 1:
![image](https://cloud.githubusercontent.com/assets/383807/20535703/2610cff4-b0a3-11e6-8f7f-dbb141c471b2.png)

Step 2 - select a person and choose the Not Duplicate button
![image](https://cloud.githubusercontent.com/assets/383807/20535726/3e841c1c-b0a3-11e6-963f-697a736fd4d8.png)

![image](https://cloud.githubusercontent.com/assets/383807/20535736/4b50f83e-b0a3-11e6-8bc8-aea2ccae4750.png)

Step 3 - return to Duplicate Finder
![image](https://cloud.githubusercontent.com/assets/383807/20535741/50ddc778-b0a3-11e6-8843-982a66b1197b.png)

**Comment by garrettjohnson** [comment]
Those are the steps; looks like it got fixed in the develop branch?

**Comment by nairdo** [comment]
Yes, I haven't spent time to try to figure out when/where it was fixed.

**Comment by garrettjohnson** [comment]
This is still an issue in v6.9 we've got around 25 records that will not disappear from the Person Duplicate list despite not having a duplicate.

**Comment by dcs619** [comment]
@garrettjohnson Have you checked the duplicates table to see which records are marked as duplicates?  I've noticed some weirdness with Rock's duplicate finder stored procedure and wonder if they're related.

**Comment by garrettjohnson** [comment]
@dcs619 I've looked at the table, I'm not super clear on how the structure works to make sense of what's going on. I'll try to anonymize a row to share if that's helpful.

**Comment by garrettjohnson** [comment]
It's unfortunate that it took this long to catch, but our `Duplicate Person List` block and `Person Duplicate Detail` block had different values for the `Confidence Score Low` and `Include Inactive` block properties. By changing them to match we're no longer encountering the error.

It might be helpful to include something in the help text to encourage updating both values at the same time.
