### ISSUE TITLE
Donate to Participant Causes Exception on Fundraising Opportunity View

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4560]
Submitted on behalf of [Sun Valley Church](https://sunvalleycc.com/)

### Description
Certain updates to a theme (layout or site master) can cause the Fundraising Opportunity View block to start getting a viewstate error on any postback. This includes clicking the "Donate to Participant" button, or even doing any other postback on the page (i.e. logging in or out). 

I haven't been able to determine exactly what needs to be added to the custom theme to cause this, but the error does seem to be related to the default Lava for the Summary view on the block. This Lava includes statements that add meta tags to the page header for social media sharing (twitter, facebook). If you remove those lines from the Lava, the error will go away. 

Woodman Valley Church is seeing the error on [this page](https://woodmenvalley.org/elsalvador2018?GroupId=215107). Sun Valley Church is seeing it on [this page](https://sunvalleycc.com/go-opportunity?GroupId=311527). 

I was only able to reproduce it on a new Rock instance using the Stark theme if I added the following to the `<head>` section of the theme's Site.Master file (Sun Valley has this code in their site.master):

```
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:image" content="">
    <meta property="og:url" content="">
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:site_name" content="">
    <meta name="twitter:image:alt" content="">
    <meta name="twitter:site" content="">
```

### Steps to Reproduce
1. Create a public fundraising opportunity group with at least one participant
1. Add the above HTML to the `<head>` section on the public theme's site.master file
1. Navigate to the missions area on public site
1. View the details of the opportunity group
1. Click the "Donate to Participant" button

I made these changes to the current demo site and you can [see the error here](https://www.rocksolidchurchdemo.com/page/470?GroupId=1215) (for now).

**Expected behavior:**

You are redirected to the donation page and can make a donation

**Actual behavior:**

A viewstate error occurs

### Versions
* **Rock Version:** v11.3
* **Client Culture Setting:** en-US

**Comment by raufrecht** [comment]
This is happening to us too. https://www.oneandall.church/global/trip?GroupId=202261. I have a workaround in place that removes all the meta tags in the summary.lava file of the fundraising page. This obviously affects the ability to share this page properly via social media.

**Comment by raufrecht** [comment]
This also happens on the fundraising person profile page.

**Comment by rutledgek** [comment]
I know this is marked fixed in v12.5 but I have a church on v 12.7 and I had to remove the metadata lava from the summary.lava file to prevent the ViewState exception.

**Comment by tstephens17** [comment]
I have a church on 12.8 and they are seeing this too. @cabal95

**Comment by tstephens17** [comment]
It was this set,
{{ Group | Attribute:'OpportunityTitle' | AddMetaTagToHead:'property','twitter:title' }}
{{ Group | Attribute:'OpportunitySummary' | AddMetaTagToHead:'property','twitter:description' }}
{{ Group | Attribute:'OpportunityTitle' | AddMetaTagToHead:'property','og:title' }}
{{ Group | Attribute:'OpportunitySummary' | AddMetaTagToHead:'property','og:description' }}

Which is on the FundraisingOpportunitySummary.lava

**Comment by ccbc-nmahoney** [comment]
@azturner @sparkdevnetwork-service - This issue is still exist in v14.1 - My church Cottonwood Creek Church is experiencing it in the latest release. 

The work around that we found was to remove the following: 

We removed the MetaTag lines from the theme's FundraisingOpportunitySummary.lava file.
 
{{ Group | Attribute:'OpportunityTitle' | AddMetaTagToHead:'property','twitter:title' }}
{{ Group | Attribute:'OpportunitySummary' | AddMetaTagToHead:'property','twitter:description' }}
{{ Group | Attribute:'OpportunityTitle' | AddMetaTagToHead:'property','og:title' }}
{{ Group | Attribute:'OpportunitySummary' | AddMetaTagToHead:'property','og:description' }}
{% assign opportunityPhotoUrl = item | Attribute:'OpportunityPhoto','Url' %}
{% if opportunityPhotoUrl != '' %}
{{ opportunityPhotoUrl | AddMetaTagToHead:'property','og:image' }}
{{ opportunityPhotoUrl | AddMetaTagToHead:'property','twitter:image' }}
{{ 'summary_large_image' | AddMetaTagToHead:'property','twitter:card' }}
{% endif %}
 
And…
 
    <li>
        <a href="https://twitter.com/intent/tweet?text={{ Group | Attribute:'OpportunityTitle' | EscapeDataString }}&url={{ 'Global' | Page:'Url' | EscapeDataString }}" class="socialicon socialicon-twitter" title="" data-original-title="Share via Twitter">
            <i class="fa fa-fw fa-twitter"></i>
        </a>
    </li>

**Comment by rutledgek** [comment]
This is broken again in v16

**Comment by chead4** [comment]
@rutledgek I am unable to recreate in v16 and v17.  Testing both with FundraisingOpportunitySummary.lava file meta tag lines mentioned above and by adding the above mentioned details to the <head> section of the theme's Site.Master file.
I was able to successfully donate to an individual and tested with someone logged in, not logged in and my participant logged in.  Also, tested both with DotLiquid and Fluid lava.

**Comment by rutledgek** [comment]
I am glad it is workng for you.  I am using 16 and I get the error and I don't have the referenced lines in the Compass Theme, at least not anywhere I can find.

**Comment by chead4** [comment]
@rutledgek  We recommend that you reach out to 9 Embers for Compass Theme support as we don't think this is a Rock issue.

**Comment by nate-steil** [comment]
I'm currently experiencing this in v16.0 as well in our testing environment. Our theme is a custom built theme, but even making sure the FundraisingOpportunitySummary file matched the Stark theme it threw the viewstate error. Removing the large chuck of lava referenced by @ccbc-nmahoney was the only thing I've found so far to get the Donate to a Participant button to work. A couple other of the fundraising pages still throw this error so I'm sure I'll have to hunt down the similar lava on those blocks as well.

**Comment by rutledgek** [comment]
I think it’s something in the master file that was fixed in the built in themes in v12 or so, but if your theme is based off of them and then taken forward it will have the same issue.  I just have no idea what that difference is.

**Comment by zackdutra** [comment]
@chead4 based on the most recent comment from @rutledgek would the Spark team be able to provide any information about what could have been fixed around v12 in the core themes that would impact this?

**Comment by chead4** [comment]
@zackdutra HI Zack - I will discuss with the team and get back to you.

**Comment by nairdo** [comment]
@zackdutra  That was quite a long time ago, but the closest thing we've found that changed in v11 _might_ have been this change to remove modernizr.js from our Themes: https://github.com/SparkDevNetwork/Rock/commit/6417bdccf971093efcf23031749dfb0509758f5b

**Comment by MichaelAllen** [comment]
I was seeing this same issue with our custom theme (based on the Compass theme, but heavily modified). I was able to fix it by editing our Site.Master and moving the `<asp:ContentPlaceHolder ID="head" runat="server"></asp:ContentPlaceHolder>` line to be immediately before the `</head>`.

In our custom theme, there were script tags between those 2 lines. As soon as I moved it, and cleared cache, this issue stopped happening. I was also able to break the stark theme by moving that line further up in the head.

Hopefully this workaround will work for others who are having the issue as well, and maybe help point the core team to what could cause this.

**Comment by nateh777** [comment]
I had a theme that was copied from Stark, there was one line difference between these lines and it caused the issue:
```
<link rel="stylesheet" href="<%# ResolveRockUrl("~~/Styles/theme.css", true) %>"/>

<asp:ContentPlaceHolder ID="head" runat="server"></asp:ContentPlaceHolder>
```

I had an additional stylesheet being placed after the link to load in Google fonts, if you place any of your custom html before these two lines it seems to work just fine:
```
<link rel="stylesheet" href="<%# ResolveRockUrl("~~/Styles/bootstrap.css", true) %>"/>
<link rel="stylesheet" href="<%# ResolveRockUrl("~~/Styles/theme.css", true) %>"/>
```
