### ISSUE TITLE
Connection Request Workflow Triggers not working and creating exception

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4920]
### Description ###

The Connection Request Workflow Triggers <code>Request Started</code> and <code>Request Assigned</code> are not working properly, and are creating an exception. I also tested with the <code>Status Changed</code> trigger and this one is working properly. This may affect other triggers - these were the only 3 I tested. It looks like something is failing and the Entity is never been passed into the Workflow. See screenshots for exception that is created.

I was told by another community user this is happening in v13.0. I can duplicate it on v13.1 and v14.0.

### A Picture Is worth a Thousand Words ###

<strong>This is from the demo site, running v14.0:</strong>
![Exception, Consume Fault](https://user-images.githubusercontent.com/23226974/153413795-3be9d6f0-ba7b-4a12-be1b-57245628c9e1.png)
Screen Shot 2022-02-10 at 08 03 19
Stack Trace:

【 code  】
at Rock.Tasks.ProcessConnectionRequestChange.LaunchWorkflow(RockContext rockContext, ConnectionWorkflow connectionWorkflow, String name, Message message) in C:\Source\Repos\Rock\Rock\Tasks\ProcessConnectionRequestChange.cs:line 252
   at Rock.Tasks.ProcessConnectionRequestChange.Execute(Message message) in C:\Source\Repos\Rock\Rock\Tasks\ProcessConnectionRequestChange.cs:line 104
   at Rock.Bus.Consumer.RockConsumer`2.Consume(ConsumeContext`1 context) in C:\Source\Repos\Rock\Rock\Bus\Consumer\RockConsumer.cs:line 86
   at MassTransit.Pipeline.ConsumerFactories.DelegateConsumerFactory`1.d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.&gt;-Send&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.&gt;-Send&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.TeeFilter`1.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.OutputPipeFilter`2.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GreenPipes.Filters.OutputPipeFilter`2.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.DynamicFilter`1.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MassTransit.Pipeline.Filters.DeserializeFilter.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.RescueFilter`2.-Send&gt;d__5.MoveNext()
【 end code 】

<strong>This is the exception from my dev server, running v13.1.</strong>

![Exception, Consume Fault](https://user-images.githubusercontent.com/23226974/153414062-87a125b7-7258-445e-84d2-525c6726ceef.png)
Screen Shot 2022-02-10 at 08 05 10
Stack Trace:

【 code  】
at Rock.Tasks.ProcessConnectionRequestChange.LaunchWorkflow(RockContext rockContext, ConnectionWorkflow connectionWorkflow, String name, Message message) in C:\Source\Repos\Rock13\Rock\Tasks\ProcessConnectionRequestChange.cs:line 252
   at Rock.Tasks.ProcessConnectionRequestChange.Execute(Message message) in C:\Source\Repos\Rock13\Rock\Tasks\ProcessConnectionRequestChange.cs:line 93
   at Rock.Bus.Consumer.RockConsumer`2.Consume(ConsumeContext`1 context) in C:\Source\Repos\Rock13\Rock\Bus\Consumer\RockConsumer.cs:line 86
   at MassTransit.Pipeline.ConsumerFactories.DelegateConsumerFactory`1.d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.&gt;-Send&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.&gt;-Send&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.TeeFilter`1.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.OutputPipeFilter`2.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GreenPipes.Filters.OutputPipeFilter`2.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.DynamicFilter`1.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MassTransit.Pipeline.Filters.DeserializeFilter.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GreenPipes.Filters.RescueFilter`2.-Send&gt;d__5.MoveNext()
【 end code 】

<strong>Here is the error the Workflow Log is displaying:</strong>
![Workflow Activity Log](https://user-images.githubusercontent.com/23226974/153414481-c4c4c92c-2a1d-4237-a9c0-1f123e0c3d2e.png)
Screen Shot 2022-02-10 at 08 06 59

### Steps to Reproduce ###

<ol><li>Create a Workflow - my first action was <code>Attribute Set From Entity</code> with the Lava: <code>{{ Entity.PersonAlias.Guid }}</code>. Turn logging on.</li><li>Create a Connection Request Workflow with Trigger <code>Request Assigned</code> - assign it to the created Workflow.</li><li>Add a Connection Request, assign it to a Connector, and click Save.</li><li>See error in Workflow, and see exception created in the log.

</li></ol><strong>Expected behavior:</strong>

Entity is passed into the Workflow and Workflow runs successfully.

<strong>Actual behavior:</strong>

Entity is not passed into the Workflow, Workflow fails, and an exception is created.

### Versions ###

<ul><li><strong>Rock Version:</strong> [v13.0, v13.1, v14.0]</li><li><strong>Client Culture Setting:</strong> [en-US]

</li></ul>

**Comment by mikedotmundy** [comment]
Upon further testing and working with @cwomack, if you are using the `Request Assigned` trigger, and create the Connection Request FIRST, then assign the connector, this works properly and there is no exception. 

So it would seem the `ConnectionRequest` entity is not passed into the workflow _at the time the request is created_ but is passed into the workflow if it is triggered on a Connection Request that is already existing.

**Comment by leahjennings** [comment]
We are running v13.1 and are still encountering this issue.

**Comment by crayzd92** [comment]
Reopening to resolve email send issue.

**Comment by crayzd92** [comment]
After further review with the community members, we are confident that the fix added to Rock has resolved the issue as expected in v13.1. Thank you all for your time and patience.

**Comment by JimMichael** [comment]
@crayzd92 Can I get some additional info on what led the "review with community members" to conclude this has been fixed and the above issue doesn't really exist? The reason I ask is that we are seeing this EXACT issue when testing a complex workflow on 13.2 BETA.
![image](https://user-images.githubusercontent.com/3903408/158464111-4225e794-f767-448a-a1b7-bc206d8c468c.png)

In our case, a specific Connection Type triggers a new workflow on Request Started
![image](https://user-images.githubusercontent.com/3903408/158464340-d705e7be-7f87-4694-ae5f-e4e4bf585ecb.png)

But when we look at that workflow, it appears the Entity isn't being passed to it like it is in our Production 12.4 system.

We also see exceptions related to this exactly like shown at the top of this issue.

**Comment by mikedotmundy** [comment]
@JimMichael You have no idea how refreshing it is to see you post this. I'll add a little more as to why. We are seeing this issue in a BUNCH of places throughout Rock, with that exact error in the WF, and, on occasion, it creates an exception. The trouble is, I cannot figure out a common theme as to what is actually causing it. 

I just discovered one last night where a WF Trigger was setup to trigger a WF, passing the entity in... successfully in v12.8, but unsuccessful in v13.1 and v13.0. 

Another one was where a WF was launched upon a GroupMember being added to a Group. But oddly, it only happens _sometimes_.

I am struggling to find a clear theme so I can open a bug report. But there is definitely something wrong with entities being passed into WF's throughout areas in Rock other than Connections.

And again, no issues in v12.8 - it all started in v13.1 (we went right past v13.0 to v13.1 so it is entirely possible it was an issue there too.)

**Comment by crayzd92** [comment]
@JimMichael @mikedotmundy Appreciate the feedback here. Know that we are taking steps to ensure this is resolved asap with https://github.com/SparkDevNetwork/Rock/commit/efb2ee8a3162c13109cbbec0bdf6af88e3bd8638

**Comment by crayzd92** [comment]
To be clear for anyone in the community following this issue. The change for this item was not in the 13.2 Alpha or Beta releases, it was added to the 13.2 early access package only. If you have the 13.2 Beta up and running you just need the updated Rock.dll to get this fix.

The fix that was in 13.1 for this issue did not resolve the problem because the connectionRequest.Guid is NULL if called in the Presave code block: https://github.com/SparkDevNetwork/Rock/blob/efb2ee8a3162c13109cbbec0bdf6af88e3bd8638/Rock/Model/Connection/ConnectionRequest/ConnectionRequest.SaveHook.cs#L251

That was a misstep on our part and we will do better.

**Comment by leahjennings** [comment]
@crayzd92 if updating an existing 13.1 instance to 13.2 early release, should I expect the Rock.dll to update automatically or is there another step that needs to be taken for that file to update and this to be resolved? I restored our dev instance to a 13.1 snapshot, updated via the normal update url (http://update.rockrms.com/F/rock/api/v2/) to 13.2 early access and can still reproduce the issue.

**Comment by JimMichael** [comment]
Interesting. I too rolled back to 13.1 and re-applied 13.2 from the /rock repo, and it DID fix the specific issue we saw launching new WFs from new connection requests.

**Comment by crayzd92** [comment]
@leahjennings I am going to have @cwomack reach out to dig on that with you. Thanks for letting us know.

**Comment by MikeDPeterson** [comment]
We fixed https://github.com/SparkDevNetwork/Rock/commit/f1aa0838ea4c844205eb31c8c1822b207dd1dc55 an additional issue that could cause this exception. That fix should take care of it.  So, this issue isn't fully fixed until 13.3

**Comment by SteveSwaringen** [comment]
Take this with a grain of salt, but I pulled forward into our 13.2 the commits @MikeDPeterson referenced above but am still seeing intermittent failures. Our use case is using the Connect button on a connection request to assign a person to a group (that part works) where the group has a workflow trigger for group member add. The trigger launches the workflow consistently, but it's 50-50 whether the workflow will see a group member entity passed to it.

We're having to come behind and manually trigger the workflows for the ones that don't take the first time. When we manually trigger them, they succeed 100% of the time. It definitely seems to have something to do with triggering the workflow proximally to the group member record being created (as with the original bug that was supposedly fixed by the commits I pulled in).

Any word on when we might see 13.3 available for early release?

**Comment by crayzd92** [comment]
@SteveSwaringen, I emailed you about this :)

**Comment by leahjennings** [comment]
@crayzd92 like Steve, we are running with the commits that were listed above so we could resolve the issue in our instance without waiting for v13.4 (worked with @cwomack to accomplish that). However, last week we had reports of a _few_ connection request workflows throwing the Bus Exception and not getting the Entity passed into it. Since the fix was pulled in, we've had 5 of the 12 Workflows triggered off a request starting in that time frame not receive the entity and throw a BusException. It's elusive and not consistently reproducible, we just catch them as they come up.

**Comment by SteveSwaringen** [comment]
The bulk of our problems turned out to be a similar but not precisely related issue with Group-Member-Add triggered workflows (whereas this dealt with Connection Request Add triggered workflows). The GMA problems were resolved internally by updating GroupMember.SaveHook.cs with changes similar to what were made in the case of the ConnectionRequest.SaveHook.cs file.

**Comment by asdf1nit** [comment]
Per the conversation in the alpha channel and a request from Nick.

I have had this issue intermittently with content channel items. I just had to run this several times to get it to misbehave.

Triggers are set up as follows. 
![image](https://user-images.githubusercontent.com/18108765/167480005-f75021e8-dbf5-45eb-bf68-1891510af9e0.png)

Once an item is added to the content channel the workflow fires.
![image](https://user-images.githubusercontent.com/18108765/167480430-1f6ddacb-f566-4541-80de-7a7af23e88e1.png)

The entity is never passed to the workflow.
![image](https://user-images.githubusercontent.com/18108765/167481158-df373515-1331-47ae-bb42-7c2ea088e605.png)


We get this in our exception log
![image](https://user-images.githubusercontent.com/18108765/167481003-89ef8cb8-2aa7-4335-af8e-acf8064c123c.png)

**Comment by ethan-sparkdevnetwork** [comment]
@SteveSwaringen Can you let me know what you are doing with the GroupMember Entity in the workflow?
@asdf1nit Thanks for this, I'll take a look a the ContentChannelItem model. It looks like this one is happening while indexing the new item for Universal Search.

**Comment by SteveSwaringen** [comment]
We have several different group-member-add-triggered workflows that have been failing since upgrading to V13 (now at V13.3). They all fail on the first Action with is an Attribute Set from Entity where the attribute we’re expecting is a Group Member. The workflow log says the action fails like this:


10 Days Ago
Start Activity > Get Group Member Action : Processing...
10 Days Ago
Start Activity > Get Group Member Action : No entity was specified or the entity is not a Rock Entity.
10 Days Ago
Start Activity > Get Group Member Action : Error Occurred: No entity was specified or the entity is not a Rock Entity.
10 Days Ago
Start Activity > Get Group Member Action : Processing Complete (Success:False)

Note that in some cases we use the same identical workflow triggered from a Group Member Status Changed (Active to Inactive or vice versa) and those always work—presumably because in those cases the group member already existed, whereas with the Group Member Add they did not (or at least were only just now created).

**Comment by nairdo** [comment]
For the sake of other readers... 

![image](https://user-images.githubusercontent.com/18108765/167480005-f75021e8-dbf5-45eb-bf68-1891510af9e0.png)

The workflow triggers that Jonathan Anderson is referring to (triggers added via [Admin Tools > General Settings > Workflow Triggers](https://prealpha.rocksolidchurchdemo.com/admin/general/workflow-triggers)), are a bit different than the ones configured in the Connection system.  

These are handled deeper in the DbContext class ([here](https://github.com/SparkDevNetwork/Rock/blob/e08cf35a3cc893c43eb42897b00ace1adf13bd80/Rock/Data/DbContext.cs#L399), [here](https://github.com/SparkDevNetwork/Rock/blob/e08cf35a3cc893c43eb42897b00ace1adf13bd80/Rock/Data/DbContext.cs#L558) and [here](https://github.com/SparkDevNetwork/Rock/blob/e08cf35a3cc893c43eb42897b00ace1adf13bd80/Rock/Data/DbContext.cs#L568) to name a few) but could possibly be suffering from the same edge-case that Mike found and resolved with this change [3bce46e in DbContext.cs line 922](https://github.com/SparkDevNetwork/Rock/commit/3bce46e1b59fd6001e2327f1c73e692209ee9342#diff-81b16412a71b63f06788276a55209317d2a27a584ebbf96bcfe0e10a36c20c2bR922) change.

...but seeing as how you've stated the issue is intermittent, as Ethan pointed out it may be some other race condition involving the Universal Search `IndexDocument()` (used in the [`ProcessEntityTypeIndex`](https://github.com/SparkDevNetwork/Rock/blob/d0bd6fac28c9c909caede07ec187d5efdb2fff12/Rock/Tasks/ProcessEntityTypeIndex.cs#L30) bus task which is used during [`BulkIndexDocumentsByContentChannel(...)`](https://github.com/SparkDevNetwork/Rock/blob/d0bd6fac28c9c909caede07ec187d5efdb2fff12/Rock/Model/CMS/ContentChannel/ContentChannel.cs#L370) which is being called during the [`PreSave()`](https://github.com/SparkDevNetwork/Rock/blob/d0bd6fac28c9c909caede07ec187d5efdb2fff12/Rock/Model/CMS/ContentChannel/ContentChannel.SaveHook.cs#L61) hook in the ContentChannel).

We're looking into that now too.

**Comment by leahjennings** [comment]
We're also getting a very similar exception to what @asdf1nit is getting, except it's not actually correlated with any workflow. The exception is nearly the same except instead of `at Rock.Model.ContentChannelItem.IndexDocument(Int32 id)` it shows `at Rock.Model.Group.IndexDocument(Int32 id)`. So this may already be resolved with what @ethan-sparkdevnetwork and @nairdo are looking into but wanted to add it for clarity. I also can't find any workflow that is being activated at the same time as the exception (checked with SQL).

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/66277785/167646789-95f134e6-750e-4345-be0f-61cc02496e73.png">

**Comment by ethan-sparkdevnetwork** [comment]
Thanks @leahjennings they are all related. I have a few fixes going into 13.4 that should address these.
95fa392f - Group Member Add
1dddbb52 - Anything having to do with search indexing

**Comment by tpcc-myles** [comment]
We are running v13.4 and are seeing this issue intermittently with the workflow trigger on Group Member Add, same as @SteveSwaringen and @mikedotmundy detailed above. That is, the workflow log indicates that no Entity was specified.  Exact messages below.

Start Activity > Get Group Member Action : No entity was specified or the entity is not a Rock Entity.
Start Activity > Get Group Member Action : Error Occurred: No entity was specified or the entity is not a Rock Entity.

Is there another fix coming or a known workaround?

**Comment by nairdo** [comment]
We're going to look into this again to try and reproduce.

**Comment by SteveSwaringen** [comment]
I do think we were continuing to see this on 13.5 although much less frequently. It feels like a timing crack (multi-threading? cache coherency?) instead of a hard logic fail. Unfortunately, the infrequency and difficulty in troubleshooting individual cases means I can't even say for certain that the incidents we think we might have had are not completely unrelated (which is why I haven't updated the ticket myself). We recently updated to 13.7 and I can't say whether we've had any more cases since that update.

I know that isn't very helpful. I'll definitely keep an eye open and update this ticket if I see anything new.

**Comment by mikedotmundy** [comment]
We are on v13.7 and have not seen this issue in quite a while.

**Comment by SteveSwaringen** [comment]
If it helps any, this is the workflow that was intermittently logging this error. The error comes from the first action in the only activity. (Note the action is conditional but the fact the error is logged indicates the action is executing. When triggered from a group member add, the workflow attribute tested by the condition should be blank.)
[Check Road Trip Credentials_202210260941.zip](https://github.com/SparkDevNetwork/Rock/files/9870569/Check.Road.Trip.Credentials_202210260941.zip)

**Comment by tpcc-myles** [comment]
We also use our workflow seasonally.  It sends email confirmations to volunteers who signup for a one-time serving opportunity.  We currently have three groups that trigger this workflow upon group member add.  So far, only two of these groups have produced the Entity error.  The other group has worked flawlessly so far.

For us also, the very first Action of the workflow (in the Start Activity) is the one resulting in the error.  It is a Set Attribute from Entity action, where we are setting a Group Member Attribute from Entity.Guid, and it executes on every run of the workflow.

We are noticing the issue now while setting up and testing our Christmas serving opportunities.  Well more than half of all tests we do result in the error, so it's pretty easily (but not consistently) reproduced.

**Comment by tpcc-myles** [comment]
FWIW, we upgraded a sandbox environment (running a fresh copy of Production) to v13.7 today and are still intermittently experiencing the issue of Entity not being passed to the workflow from the Group Member Add trigger.

**Comment by nairdo** [comment]
@tpcc-myles  We've not been able to reproduce this since the fix was applied in version 13.4 (https://github.com/SparkDevNetwork/Rock/commit/f1aa0838ea4c844205eb31c8c1822b207dd1dc55) -- so we're going to close this issue and ask that you do the following if the issue happens for you again:
1. Open a new issue
2. Include any/all relevant exceptions that you are seeing
4. Include a copy of your workflow action,
5. Mention which version of Rock you're using
6. Refer back to this issue

Thanks for your assistance in tracking this down.
