### ISSUE TITLE
Obsidian Registration Entry Block Address Person Field Issues

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5541]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

- The State in the Address field defaults to AZ.
- The Address field will raise an error that Address Line 1 and City is required when it is not set to required.
See screenshot below.

### Expected Behavior

The address field State should be empty or defaults to the orgazanition state. The address field should not be required if it is not set as required.

### Actual Behavior

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/aff81397-5c58-4ede-ba3d-7be38c7337c9)

### Steps to Reproduce

- At first I set the address field to required, then I got tired of entering the address everytime I  change something in the form when testing so I unchecked the Required.

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by joezimjs** [comment]
Fixed with this commit: https://github.com/SparkDevNetwork/Rock/commit/fb106eb69e0db60929cbc7a744af6bc14334b51c

**Comment by joezimjs** [comment]
@JDShuman Under Admin Tools > General Settings > Global Attributes you'll find a setting for Organization Address

![image](https://github.com/SparkDevNetwork/Rock/assets/1313898/4ec74616-afb3-440c-b65e-200b043082f6)

The default country and state are pulled from this address. I'm so sorry that I didn't address (no pun intended) this before marking it as fixed. Let me know if there's anything else I can do to help. If you don't need anything else, please re-close this issue. Thanks!

**Comment by JDShuman** [comment]
Thanks @joezimjs. I wondered if that is where it was pulling from, but we've had that set for several years now.
![image](https://github.com/SparkDevNetwork/Rock/assets/93220961/8fb44b89-a6a9-4e5d-8bc2-c91b32efb074)

Any ideas on why that wouldn't be pulling into our event registrations correctly?

**Comment by nairdo** [comment]
@JDShuman I'm afraid our fix had two parts to it and only one was in the v15.2 release.  I just confirmed the bug is still in the v15.2 release but it is fixed in the upcoming v15.3 release (releasing next week):

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/c18d995a-8552-4d35-9442-752e26ac31ad)

Sorry about that!  We'll re-label this and correct the release note to be on the v15.3 release.

**Comment by joezimjs** [comment]
@JDShuman Nick and I dug a little deeper and found out why I marked it as fixed but it was still causing issues for you. The change in v15.2 / v16.0 did fix this issue for Registration Attributes, but I didn't realize that the Person Field was actually using a different mechanism for gathering the default value. This is fixed in v15.3 / v16.1. I'm sorry for the confusion.

![image](https://github.com/SparkDevNetwork/Rock/assets/1313898/5ddd3679-0333-4e83-8137-e947006b8084)
