### ISSUE TITLE
Communications with a large number of recipients time out and don't send.

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#5651]
### Description

Communication Timeout error in the exception log for communications that have a large number of recipients.

Example https://staff.freechapel.org/communications/295239
Recipients: 18425
This is an email bulk communication using the "Default" template.
Navigating from Editor to Confirmation screen takes 26 seconds.

### Actual Behavior

Depending on how the communication is being sent one of two errors are logged.

Sent by the Send Communications Job
```
One or more exceptions occurred sending communications... Exception occurred sending communication ID:311187: An error occurred while executing the command definition. See the inner exception for details. Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding. The wait operation timed out

 at Rock.Jobs.SendCommunications.Execute() in \Rock\Jobs\SendCommunications.cs:line 189
   at Rock.Jobs.RockJob.ExecuteInternal(IJobExecutionContext context) in \Rock\Jobs\RockJob.cs:line 162
   at Quartz.Core.JobRunShell.Run()
```

Sent by the Bus
```
A ConsumeFault occurred in the Rock.Tasks.ProcessSendCommunication. Original Message: Rock.Tasks.ProcessSendCommunication+Message.
Exception: System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition.
See the inner exception for details. 
System.Data.SqlClient.SqlException: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
System.ComponentModel.Win32Exception: The wait operation timed out --- End of inner exception stack trace ---
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
 at System.Data.SqlClient.SqlDataReader.get_MetaData()
 at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
 at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
 at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
 at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
 at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
 at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior) --- End of inner exception stack trace ---
 at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
 at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
 at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
 at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
 at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
 at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
 at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
 at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at Rock.Model.Communication.RefreshCommunicationRecipientList(RockContext rockContext) in \Rock\Model\Communication\Communication\Communication.Logic.cs:line 350
 at Rock.Model.Communication.<SendAsync>d__21.MoveNext() in \Rock\Model\Communication\Communication\Communication.Logic.cs:line 532 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Rock.Utility.AsyncHelper.RunSync(Func`1 func) in \Rock\Utility\AsyncHelper.cs:line 74
 at Rock.Tasks.ProcessSendCommunication.Execute(Message message) in \Rock\Tasks\ProcessSendCommunication.cs:line 37
 at Rock.Bus.Consumer.RockConsumer`2.Consume(ConsumeContext`1 context) in \Rock\Bus\Consumer\RockConsumer.cs:line 87
 at MassTransit.Pipeline.ConsumerFactories.DelegateConsumerFactory`1.<Send>d__2`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.<GreenPipes-IFilter<MassTransit-ConsumeContext<TMessage>>-Send>d__4.MoveNext()
```

It appears the timeout occurs while checking to see if all of the communication members are in the recipient list here: https://github.com/SparkDevNetwork/Rock/blob/33b0d328a3b7835613afeede9af57b206f6125f3/Rock/Model/Communication/Communication/Communication.Logic.cs#L350https://github.com/SparkDevNetwork/Rock/blob/33b0d328a3b7835613afeede9af57b206f6125f3/Rock/Model/Communication/Communication/Communication.Logic.cs#L350

### Expected Behavior

The communication is sent successfully.

### Steps to Reproduce

-Create a communication with a large number of recipients.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@tikool17 Rock is all about community.  If possible, please include you name in your GitHub account.

**Comment by jasonhendee** [comment]
Hey @tikool17, thanks for reporting. Are you able to consistently reproduce this issue? We've spent a bit of time attempting to reproduce while sending to 100k+ recipients, without success thus far. Are there any additional "Steps to Reproduce" you can provide?

**Comment by tikool17** [comment]
@jasonhendee thanks for looking into this. I don't have a definite steps to reproduce other than a large number of recepients. But if it helps we do use Communication lists, segments and prevent duplicates often. See below on some typical segment setup which I could see that would add some extra strain on the system to process.
![Uploading Screen Shot 2023-11-21 at 4.58.25 PM.png…]()

**Comment by jasonhendee** [comment]
Thanks, @tikool17; this is very helpful.

If you were to send the above communication, would it fail every time? Or does it seem to be hit-or-miss?

**Comment by jasonhendee** [comment]
@tikool17, we've addressed this issue as follows:

1. We identified and improved several areas within the **Communication Entry Wizard** block and the general `Communication` send processes themselves where performance improvements could be made. We hope you'll notice that creating new communications within the wizard feels snappier moving forward.
2. We added new [Observability](https://community.rockrms.com/Rock/BookContent/9#observability) hooks to several key areas within the **Communication Entry Wizard** block and general `Communication` send processes that will help us track down and dig further into remaining performance bottlenecks that might yet reveal themselves.

Furthermore, we have plans to rewrite the **Communication Entry Wizard** block in Obsidian soon, so we're hesitant to spend too much more time addressing some of the known super edge case performance issues that still exist within the legacy version of this block.

Please feel free to reopen this issue if you find the original issues still present themselves within your environment after updating to Rock v16.2.

**Comment by karenn-ccbc** [comment]
This does not appear to be fixed. We are in v 16.5 and just had this happen with **9351** recipients in our church newsletter today. I cannot get it to go out today.
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/9523fba5-f4ea-42d9-ae2e-7699ffd946f8)
Is there some setting we need to increase in our servers or in Rock on our end?

**Comment by karenn-ccbc** [comment]
Just to follow up our email finally sent at 2:40 AM. I am not sure what happened to allow it to go through yet.
https://files.slack.com/files-pri/T04L8T2P7FH-F0779PGNS2Y/screenshot_20240608_080119_chrome.jpg

**Comment by karenn-ccbc** [comment]
This happened again to us this week. This week we did not select the option to prevent duplicates and it still failed/timed out. We had to manually split our dataview in halves and send it to each half separately. We could not use the communication list for 9300 people.

**Comment by jonedmiston** [comment]
@karenn-ccbc can you provide us your server specs for both your web vm and database?

**Comment by karenn-ccbc** [comment]
I am getting it and will reply.


Karen Norris

Director of Rock RMS

Christ Chapel Bible Church

817-546-0811



***@***.***?anonymous&ep=signature>               Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________

**Comment by karenn-ccbc** [comment]
Here are our specs:
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/58f0de36-de85-49ca-a107-cc8eba29cedc)

**Comment by tikool17** [comment]
This has definitely gotten better for us since the changes above. But it has happened a couple other times since. The Send Communications jobs will time out for a number of hours and then usually will eventually send.

**Comment by zackdutra** [comment]
@jonedmiston what are the recommended server specs to send to a list of 35k+ recipients? We have several of our lists moved over from Mailchimp to Rock, but not our main campus yet. We've been holding out to be sure this issue was closed but it looks like it's still a potential problem.  @karenn-ccbc  let me know the workaround she's using is not syncing to a communication list and splitting up into multiple data views, but that will be too much for our team to manage.

**Comment by chead4** [comment]
I just wanted to provide an update as well. At this time, we don't believe that Observability is the cause of the issue.  Our investigation is still ongoing, and Observability provided valuable insights into improving some queries.  

We are very grateful to Karen and Philip for providing many details in order to triage this issue.

**Comment by chead4** [comment]
We wanted to provide a final update on this issue. 

Observability was not the cause of the issue; instead, we discovered that the Bulk Insert New Members call was timing out. The performance improvement, verified by Karen and Philip, will be included in v16.6.

Our sincere appreciation to both Karen and Philiip for working with us on this issue.
